[package]
name = "menemen"
version = "2.0.0"
authors = ["Behemehal", "Ahmetcan Aksu"]
edition = "2021"
description = "Menemen is a lightweight streaming HTTP/HTTPS client for Rust with both blocking and async modes."
categories = ["network-programming"]
keywords = ["network", "http", "https", "stream", "async", "blocking", "client"]
license = "GPL-2.0"
readme = "README.md"
documentation = "https://docs.rs/menemen"
repository = "https://github.com/behemehal/Menemen"

[features]
default = ["async", "json", "multipart"]

# CLI tool feature
cli = ["clap", "clap_complete", "blocking", "https", "json", "multipart"]

# User-facing feature
https = []

#https-blocking = ["native-tls"]
#https = ["tokio-native-tls"]
json = ["serde", "serde_json"]
async = ["tokio", "futures", "dep:tokio-native-tls"]
blocking = ["dep:native-tls"]
multipart = ["rand", "mime_guess"]
gzip = ["libflate"]
danger-transport-no-tls = [
] # # Allow client to send requests to https endpoints without TLS (not recommended)

[dependencies]
anyhow = "1.0.95"
bufstream = { version = "0.1.4" }
native-tls = { version = "0.2.13", optional = true }
tokio = { version = "1.40.0", features = [
    "net",
    "io-util",
    "fs",
    "time",
], optional = true }
tokio-native-tls = { version = "0.3.1", optional = true }
serde = { version = "1.0.217", features = ["derive"], optional = true }
serde_json = { version = "1.0.138", optional = true }
rand = { version = "0.9.0", optional = true }
mime_guess = { version = "2.0.5", optional = true }
libflate = { version = "2.1.0", optional = true }
futures = { version = "0.3.31", optional = true }
bytes = "1.10.1"
pin-project-lite = "0.2.16"
clap = { version = "4.5", features = ["derive", "cargo"], optional = true }
clap_complete = { version = "4.5", optional = true }

[dev-dependencies]
tokio = { version = "1.39.2", features = ["full"] }
tokio-macros = "2.5.0"
serde = { version = "1.0.207", features = ["derive"] }
indicatif = "0.17.11"

[[example]]
name = "download_file"
path = "examples/download_file.rs"

[[example]]
name = "body"
path = "examples/body.rs"

[[example]]
name = "chunked"
path = "examples/chunked.rs"

[[example]]
name = "download_file_async"
path = "examples/download_file_async.rs"
required-features = ["async"]

[[example]]
name = "echo"
path = "examples/echo.rs"

[[example]]
name = "form_data"
path = "examples/form_data.rs"

[[example]]
name = "parse_url"
path = "examples/parse_url.rs"

[[example]]
name = "post"
path = "examples/post.rs"

[[example]]
name = "gzip"
path = "examples/gzip.rs"

[[example]]
name = "json"
path = "examples/json.rs"
required-features = ["json", "async"]

[[example]]
name = "long_polling"
path = "examples/long_polling.rs"

[[example]]
name = "multipart_form_data"
path = "examples/multipart_form_data.rs"

[[bin]]
name = "menemen"
path = "src/bin/menemen.rs"
required-features = ["cli", "blocking"]
