[package]
name = "menemen"
version = "1.0.3"
authors = ["Behemehal", "Ahmetcan Aksu"]
edition = "2021"
description = "A streaming http request library"
categories = ["network-programming"]
keywords = ["network", "http", "stream"]
license = "GPL-2.0"
readme = "README.md"
documentation = "https://docs.rs/menemen"
repository = "https://github.com/behemehal/Menemen"

[features]
default = ["async", "https"]
https = ["native-tls"]
async = ["tokio"]

[dependencies]
anyhow = "1.0.52"
bufstream = { version = "0.1.4" }
native-tls = { version = "0.2.12", optional = true }
tokio = { version = "1", features = ["net"], optional = true }

[dev-dependencies]
libflate = "2.1.0"

[[example]]
name = "download_file"
path = "examples/download_file.rs"

[[example]]
name = "echo"
path = "examples/echo.rs"

[[example]]
name = "parse_url"
path = "examples/parse_url.rs"

[[example]]
name = "post"
path = "examples/post.rs"

[[example]]
name = "gzip"
path = "examples/gzip.rs"
